---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №7"
subtitle: "Модель распространения рекламы"
---

# Цель работы

Цель данной лабораторной работы — исследовать математическую модель распространения рекламы, сравнить эффективность различных механизмов информирования (платная реклама и «сарафанное радио»), а также определить момент максимального роста информированности.

# Задание

— Создать рабочий каталог для всего курса.
— Установить необходимые пакеты.
— Выполнить предложенный код.
— Преобразовать код в литературный стиль.
— Сгенерировать из литературного кода:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook.
— Интегрировать документацию в формате Quarto в отчёт.
— Добавить в код в литературном стиле вычисление для набора параметров.
— Сгенерировать из литературного кода с параметрами:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook с параметрами.
— Интегрировать документацию с параметрами в формате Quarto в отчёт.

# Выполнение лабораторной работы

{{< include ../project/markdown/lab7/lab7.qmd >}}

# Выводы

По итогам лабораторной работы была исследована математическая модель распространения рекламы, учитывающая два механизма информирования: платную рекламу и «сарафанное радио». Построены графики изменения числа информированных покупателей во времени для различных соотношений коэффициентов $\alpha_1$ и $\alpha_2$. Определен момент максимальной эффективности рекламной кампании, соответствующий точке перегиба логистической кривой. Проведен сравнительный анализ трех сценариев: с учетом только платной рекламы, только «сарафанного радио» и комбинированного воздействия. Показано, что комбинированная модель наиболее адекватно описывает реальные процессы распространения информации и позволяет оптимизировать рекламную стратегию.
