---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №6"
subtitle: "Модель эпидемии"
---

# Цель работы

Цель данной лабораторной работы — исследовать модель взаимодействия популяций хищников и жертв, построить фазовые портреты и графики изменения численности во времени, а также найти стационарное состояние системы.
# Задание

— Создать рабочий каталог для всего курса.
— Установить необходимые пакеты.
— Выполнить предложенный код.
— Преобразовать код в литературный стиль.
— Сгенерировать из литературного кода:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook.
— Интегрировать документацию в формате Quarto в отчёт.
— Добавить в код в литературном стиле вычисление для набора параметров.
— Сгенерировать из литературного кода с параметрами:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook с параметрами.
— Интегрировать документацию с параметрами в формате Quarto в отчёт.

# Выполнение лабораторной работы

{{< include ../project/markdown/lab6/lab6.qmd >}}

# Выводы

По итогам лабораторной работы была исследована модель Лотки-Вольтерры, описывающая взаимодействие популяций хищников и жертв. Найдено стационарное состояние системы, проведено численное моделирование динамики численности. Построены временные графики x(t) и y(t), а также фазовый портрет, демонстрирующий замкнутые траектории, что соответствует периодическим колебаниям численности. Рассмотрена концепция структурной устойчивости и показано, что жесткая модель может приводить к качественно ошибочным предсказаниям без анализа мягких возмущений.
