---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Лабораторная работа №3"
subtitle: "Модель боевых действий."
date: today
date-format: "YYYY-MM-DD" # Example: 2025-09-06
---

# Информация

## Докладчик

:::::::::::::: {.columns align=center}
::: {.column width="70%"}

  * Постнова Елизавета Андреевна
  * Российский университет дружбы народов им. П. Лумумбы
  * [1132236051@rudn.ru](mailto:1132236051@rudn.ru)

:::
::: {.column width="30%"}

:::
::::::::::::::

# Цель работы

Цель данной лабораторной работы - исследовать Модель боевых действий.

# Задание

— Создать рабочий каталог для всего курса.
— Установить необходимые пакеты.
— Выполнить предложенный код.
— Преобразовать код в литературный стиль.
— Сгенерировать из литературного кода:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook.
— Интегрировать документацию в формате Quarto в отчёт.
— Добавить в код в литературном стиле вычисление для набора параметров.
— Сгенерировать из литературного кода с параметрами:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook с параметрами.
— Интегрировать документацию с параметрами в формате Quarto в отчёт.

# Выводы

По итогам лабораторной работы была построена Модель боевых действий.