---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №1"
subtitle: "Подготовка стенда"
---

# Цель работы

Исследовать математическую модель задачи преследования браконьерской лодки катером береговой охраны при заданном отношении скоростей и начальном расстоянии k. Для двух возможных начальных положений катера относительно полюса вывести дифференциальные уравнения движения, построить траектории в полярных координатах и определить точки встречи с лодкой, движущейся прямолинейно в неизвестном направлении.

# Задание

Вариант 52
На море в тумане катер береговой охраны преследует лодку браконьеров.
Через определенный промежуток времени туман рассеивается, и лодка
обнаруживается на расстоянии 17,4 км от катера. Затем лодка снова скрывается в
тумане и уходит прямолинейно в неизвестном направлении. Известно, что скорость
катера в 4,9 раза больше скорости браконьерской лодки.
1. Запишите уравнение, описывающее движение катера, с начальными
условиями для двух случаев (в зависимости от расположения катера
относительно лодки в начальный момент времени).
2. Постройте траекторию движения катера и лодки для двух случаев.
3. Найдите точку пересечения траектории катера и лодки     

# Выполнение лабораторной работы

Номер задания=(SnmodN)+1

Sn=1132236051, N=70

1132236051mod70=1132236000
S
1132236051−1132236000=51+1=52

{{< include ../project/markdown/task/task.qmd >}}

# Выводы

В ходе выполнения лабораторной работы была исследована математическая модель задачи преследования браконьерской лодки катером береговой охраны. Для заданных параметров — начального расстояния между объектами и отношения их скоростей — были получены уравнения движения катера, состоящие из двух этапов: прямолинейного движения к полюсу и последующего движения по спирали. Рассмотрены два возможных начальных положения катера относительно полюса, определены расстояния, на которых происходит смена режима движения. На основе выбранных направлений движения лодки построены траектории обоих объектов в полярных и декартовых координатах, графически определены точки их пересечения. Результаты наглядно демонстрируют, что описанная стратегия движения катера обеспечивает перехват лодки независимо от направления её движения.

# Список литературы{.unnumbered}

::: {#refs}
:::
