---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №8"
subtitle: "Модель конкуренции двух фирм"
---

# Цель работы

Цель данной лабораторной работы — исследовать модель конкуренции двух фирм, производящих взаимозаменяемые товары, построить графики изменения оборотных средств для различных сценариев взаимодействия, а также найти стационарные состояния системы.

# Задание

— Создать рабочий каталог для всего курса.
— Установить необходимые пакеты.
— Выполнить предложенный код.
— Преобразовать код в литературный стиль.
— Сгенерировать из литературного кода:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook.
— Интегрировать документацию в формате Quarto в отчёт.
— Добавить в код в литературном стиле вычисление для набора параметров.
— Сгенерировать из литературного кода с параметрами:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook с параметрами.
— Интегрировать документацию с параметрами в формате Quarto в отчёт.

# Выполнение лабораторной работы

{{< include ../project/markdown/lab8/lab8.qmd >}}

# Выводы

По итогам лабораторной работы была исследована модель конкуренции двух фирм, производящих взаимозаменяемые товары. Рассмотрена базовая модель одной фирмы, позволившая определить условия стабильного функционирования и пороговые значения оборотных средств, необходимые для входа на рынок. Построены и проанализированы два сценария конкурентного взаимодействия: при чисто рыночной конкуренции и при учете социально-психологических факторов. Показано, что в первом случае обе фирмы достигают устойчивого равновесия, разделяя рынок, а во втором — асимметрия в предпочтениях потребителей может привести к банкротству одной из фирм. Найдены стационарные состояния системы. Полученные результаты демонстрируют важность учета не только экономических, но и социальных факторов при моделировании конкурентных процессов.

